services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    restart: always
    command: --sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: